export default ArticleList = [
    {
        "categoryId": 1,
        "articleId": 1,
        "articleName":"artilce name",
        "articleAuthor":"artilce authoor",
        "articleImageName":"artilce name",
        "articleDescription":"artilce description",
    }, 
    {
        "categoryId": 1,
        "articleId": 2,
        "articleName":"artilce name",
        "articleAuthor":"artilce authoor",
        "articleImageName":"artilce name",
        "articleDescription":"artilce description",
    },
    {
        "categoryId": 1,
        "articleId": 3,
        "articleName":"artilce name",
        "articleAuthor":"artilce authoor",
        "articleImageName":"artilce name",
        "articleDescription":"artilce description",
    },
    {
        "categoryId": 1,
        "articleId": 4,
        "articleName":"artilce name",
        "articleAuthor":"artilce authoor",
        "articleImageName":"artilce name",
        "articleDescription":"artilce description",
    },
    {
        "categoryId": 1,
        "articleId": 5,
        "articleName":"artilce name",
        "articleAuthor":"artilce authoor",
        "articleImageName":"artilce name",
        "articleDescription":"artilce description",
    },
    {
        "categoryId": 1,
        "articleId": 1,
        "articleName":"artilce name",
        "articleAuthor":"artilce authoor",
        "articleImageName":"artilce name",
        "articleDescription":"artilce description",
    }
];